### ISSUE TITLE
Support setting Lumigo tags

### ISSUE THREAD

**Issue by hoegertn** [lumigo-io/lumigo-cdk-constructs#8]
It would be nice to be able to set the env var LUMIGO_TAG using this construct to group resources coming from on stack.

**Comment by mmanciop** [comment]
@hoegertn what is the perceived benefit over using a `Tags.of(Construct).add('LUMIGO_TAG', <my_value>)`?

**Comment by hoegertn** [comment]
It is not about tags in AWS but an environment variable of the Lambda function that leads to the Tag being set in Lumigo

**Comment by mmanciop** [comment]
Yes, but the Lumigo tag can also be set via the `LUMIGO_TAG` AWS Tag. Superficially, it works just the same. (Detail differ ofc, but not massively.)
